use_frameworks!

platform :ios, '8.0'

target 'LanYouTest_Example' do
  pod 'LanYouTest', :path => '../'

  target 'LanYouTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'SVProgressHUD'
  end
end
